name: Test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'


jobs:
  test:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pytest_appenv.yml@master
    with:
      versions: >-
        ["3.9", "3.10"]

  coverage:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/coverage.yml@master
    with:
      min_coverage: 80

  pre-commit:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pre_commit.yml@master

  sonarqube:
    needs: coverage
    uses: risclog-solution/gha_workflow_templates/.github/workflows/sonarqube.yml@master
    secrets:
      SONARQUBETOKEN: ${{ secrets.SONARQUBETOKEN }}

  publish-test-results:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/publish_test_results.yml@master
